name: Create CRA Template and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  create-react-app-test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create CRA from Template
        run: yarn create react-app temp-project/react-app --template file:.
      - name: Lint Test
        run: yarn lint
        working-directory: temp-project/react-app
      - name: Testing
        run: yarn test
        working-directory: temp-project/react-app